spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  application:
    name: first-service
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: https://heroku-gatewa2.herokuapp.com/eureka